#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if [[ $(git rev-parse --abbrev-ref HEAD) = develop ]] || [[ $(git rev-parse --abbrev-ref HEAD) = main ]]; 
then npm run format && npm run lint && npm run test;
fi;