name: QUALITY_CHECKS

on:
  pull_request:
    branches: [ "develop" , "*release*", "main" ]
    types: [opened, reopened, edited, synchronize]

  workflow_dispatch:

jobs:
  add-label:
    runs-on: ubuntu-latest

    steps:
    - name: CHECKOUT_CODE
      uses: actions/checkout@v2

    - name: ADD LABEL QUALITY_CHECKS_FAIL TO PULL REQUEST
      run: |
        # Extract pull request number
        PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")

        # Add a label to the pull request using GitHub API
        curl -X POST \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/labels \
          -d '{"labels": ["QUALITY_CHECKS_FAIL"]}'

    - run: echo "SETTING UP NODE VERSION"
    - uses: actions/setup-node@v2
      with:
        node-version: '18'

    - run: echo "INSTALL DEPENDENCIES"
    - name: Install Dependencies
      run: npm install

    - run: echo "CHECK LINTER"
    - name: Linter
      run: npm run lint

    - run: echo "CHECK FORMAT"
    - name: Format
      run: npm run format

    - run: echo "CHECK TEST"
    - name: Format
      run: npm run test

    - name: echo "CHECK COVERAGE"
      uses: greatwizard/coverage-diff-action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: REMOVE LABEL QUALITY_CHECKS_FAIL TO PULL REQUEST
      run: |
        # Extract pull request number
        PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")

        # Remove a label from the pull request using GitHub API
        curl -X DELETE \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/labels/QUALITY_CHECKS_FAIL

    - name: ADD LABEL QUALITY_CHECKS_PASS TO PULL REQUEST
      run: |
        # Extract pull request number
        PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
    
        # Add a label to the pull request using GitHub API
        curl -X POST \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/labels \
          -d '{"labels": ["QUALITY_CHECKS_PASS"]}'


